### ISSUE TITLE
Can't mint

### ISSUE THREAD

**Issue by Megumiiiiii** [mooonero/mordinals#10]
Why ?

![Screenshot_40](https://user-images.githubusercontent.com/98658943/226163447-a946276d-c83e-425f-b17a-60454de789e4.png)

**Comment by nahuhh** [comment]
you need the text file 

'mint_ordinal 0.00001 /root/810.png /root/text.txt'

**Comment by Megumiiiiii** [comment]
> you need the text file
> 
> ```
> mint_ordinal 0.00001 /root/810.png /root/text.txt
> the problem is `Unknwon command` there's no `mint_ordinal` command

**Comment by nahuhh** [comment]
Run it in the mordinal cli wallet

**Comment by nahuhh** [comment]
https://github.com/plowsof/monero/actions/runs/4457755707

if you cant built it, merry christmas

**Comment by Megumiiiiii** [comment]
Thank you,
