### ISSUE TITLE
Missing inscriptions & mordinals post-update

### ISSUE THREAD

**Issue by ill5-com** [mooonero/mordinals#18]
Hello, somehow during the update to the new inscriptions system my wallet now shows me having 0 inscriptions, despite the inputs and outputs being visible with show_transfers. Reverting to the old binaries from before the update shows 0 mordinals where before it showed all the ones I minted. Attempting to create a new wallet and restoring from seed phrase doesn't change anything, even after forced rescans. When minting the mordinals pre-update I was using trusted third-party Monero nodes.

If you're a maintainer, please post your PGP public key so that I may encrypt messages with debug info, thanks.

Edit: syncing the Monero blockchain to a local node using the mordinals daemon and rescanning in my wallet didn't work either.

**Comment by SanLeo461** [comment]
I'm having the same issue, tried both on master branch and ordinal_transfer branch

**Comment by mooonero** [comment]
@SanLeo461  @ill5-com  Hi, I'm sorry for the inconvenience caused by the issue. Firstly, it's important to note that Mordinal's wallet must be synced only from the Mordinal daemon and only from the latest version, due to the inscription validation on the node-side. If the wallet has been synced from a pure Monero node, it won't recognize any of its inscriptions. Moreover, it's even more dangerous to use a wallet synced from a Monero daemon as it can spend outs that are supposed to be inscriptions as regular outputs, leading to the burning of inscriptions. Try to delete wallet cache file and open the wallet with mordinals-synced node and let me know how it worked

**Comment by ill5-com** [comment]
> @SanLeo461 @ill5-com Hi, I'm sorry for the inconvenience caused by the issue. Firstly, it's important to note that Mordinal's wallet must be synced only from the Mordinal daemon and only from the latest version, due to the inscription validation on the node-side. If the wallet has been synced from a pure Monero node, it won't recognize any of its inscriptions. Moreover, it's even more dangerous to use a wallet synced from a Monero daemon as it can spend outs that are supposed to be inscriptions as regular outputs, leading to the burning of inscriptions. Try to delete wallet cache file and open the wallet with mordinals-synced node and let me know how it worked

Thanks for the reply. After deleting the cache files and resyncing using a Mordinals daemon there is no change, it still shows 0 inscriptions. The transactions containing the mordinals are visible.

Below is a screenshot, whether it's useful or not who knows.

![image](https://user-images.githubusercontent.com/105583568/230267347-c5299ada-b8a7-4778-800a-44c173ae52cd.png)

**Comment by mooonero** [comment]
@ill5-com  can you tell me, did your inscriptions occur after block height 2855400? If so, they won't be counted as inscriptions due to the increase in inscription fees that took effect at block height 2855400

**Comment by ill5-com** [comment]
> @ill5-com can you tell me, did your inscriptions occur after block height 2855400? If so, they won't be counted as inscriptions due to the increase in inscription fees that took effect at block height 2855400

Hello, they were created a few hours after the launch of Mordinals, not after the change to "inscriptions." I was mistakenly assuming that Mordinals would have been grandfathered over. Is there anything special that needs to be done to get them to show properly?

**Comment by mooonero** [comment]
@ill5-com That's really weird. Is there any chance you could reach out to me on Twitter via direct messages so that we can discuss this issue in more detail and investigate further? https://twitter.com/m0rdinals

**Comment by ill5-com** [comment]
fixed in [https://github.com/mooonero/mordinals/commit/37b2c08bfeb080f7d24d0118bed592ea6ee6271b](https://github.com/mooonero/mordinals/commit/37b2c08bfeb080f7d24d0118bed592ea6ee6271b)
