### ISSUE TITLE
Compiler warning 

### ISSUE THREAD

**Issue by Auroleius** [mooonero/mordinals#4]
I receive this warning while trying to compile this from source on macOS, is Linux preferred?

error: no matching member function for call to 'init'
  r = core_storage->init(db, opt_testnet ? cryptonote::TESTNET : opt_stagenet ? cryptonote::STAGENET : cryptonote::MAINNET);

**Comment by cryptoguard** [comment]
I get the same error on Linux.

**Comment by mooonero** [comment]
@cryptoguard  @Auroleius  for now please build only simplewallet and daemon targets, we'll fix tests soon.

**Comment by mooonero** [comment]
fixed
