### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by tuxpizza** [mooonero/mordinals#5]
Attempting to compile on Fedora 37 with all the proper dependencies installed, I'm getting errors related to a missing function "no matching function for call to ‘cryptonote::Blockchain::init(cryptonote::BlockchainDB*&, cryptonote::network_type&)"  for multiple files. Compiling gets stopped at 74%.

using make with no arguments targeting master.

The repo was pulled recursively.

`[ 74%] Building CXX object tests/block_weight/CMakeFiles/block_weight.dir/block_weight.cpp.o
In file included from /home/tux/mordinals/src/cryptonote_core/tx_pool.h:47,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_usage.cpp:34:
/home/tux/mordinals/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Wdeprecated-declarations]
   43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
      |                             ^~~~~~~~~~~~~~
In file included from /usr/include/c++/12/string:48,
                 from /usr/include/c++/12/stdexcept:39,
                 from /usr/include/boost/optional/bad_optional_access.hpp:15,
                 from /usr/include/boost/optional/optional.hpp:32,
                 from /usr/include/boost/range/detail/default_constructible_unary_fn.hpp:13,
                 from /usr/include/boost/range/adaptor/transformed.hpp:15,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_usage.cpp:29:
/usr/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
/home/tux/mordinals/src/blockchain_utilities/blockchain_usage.cpp: In function ‘int main(int, char**)’:
/home/tux/mordinals/src/blockchain_utilities/blockchain_usage.cpp:177:25: error: no matching function for call to ‘cryptonote::Blockchain::init(cryptonote::BlockchainDB*&, cryptonote::network_type&)’
  177 |   r = core_storage->init(db, net_type);
      |       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /home/tux/mordinals/src/cryptonote_core/cryptonote_core.h:46,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_usage.cpp:35:
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::network_type, bool, const cryptonote::test_options*, cryptonote::difficulty_type, const cryptonote::GetCheckpointsCallback&)’
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:34: note:   no known conversion for argument 1 from ‘cryptonote::BlockchainDB*’ to ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::HardFork*&, cryptonote::network_type, bool)’
  155 |     bool init(const std::string& config_folder, BlockchainDB* db, HardFork*& hf, const network_type nettype = MAINNET, bool offline = false);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note:   candidate expects 5 arguments, 2 provided
make[3]: *** [src/blockchain_utilities/CMakeFiles/blockchain_usage.dir/build.make:76: src/blockchain_utilities/CMakeFiles/blockchain_usage.dir/blockchain_usage.cpp.o] Error 1
make[3]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make[2]: *** [CMakeFiles/Makefile2:3981: src/blockchain_utilities/CMakeFiles/blockchain_usage.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
In file included from /home/tux/mordinals/src/cryptonote_basic/cryptonote_format_utils.h:33,
                 from /home/tux/mordinals/src/cryptonote_core/cryptonote_tx_utils.h:32,
                 from /home/tux/mordinals/src/cryptonote_core/blockchain.h:59,
                 from /home/tux/mordinals/src/blockchain_utilities/bootstrap_file.h:39,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_export.cpp:29:
/home/tux/mordinals/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Wdeprecated-declarations]
   43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
      |                             ^~~~~~~~~~~~~~
In file included from /usr/include/c++/12/bits/unique_ptr.h:37,
                 from /usr/include/c++/12/memory:76,
                 from /usr/include/boost/iostreams/stream_buffer.hpp:15,
                 from /home/tux/mordinals/src/blockchain_utilities/bootstrap_file.h:31:
/usr/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
/home/tux/mordinals/src/blockchain_utilities/blockchain_export.cpp: In function ‘int main(int, char**)’:
/home/tux/mordinals/src/blockchain_utilities/blockchain_export.cpp:165:25: error: no matching function for call to ‘cryptonote::Blockchain::init(cryptonote::BlockchainDB*&, cryptonote::network_type)’
  165 |   r = core_storage->init(db, opt_testnet ? cryptonote::TESTNET : opt_stagenet ? cryptonote::STAGENET : cryptonote::MAINNET);
      |       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::network_type, bool, const cryptonote::test_options*, cryptonote::difficulty_type, const cryptonote::GetCheckpointsCallback&)’
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:34: note:   no known conversion for argument 1 from ‘cryptonote::BlockchainDB*’ to ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::HardFork*&, cryptonote::network_type, bool)’
  155 |     bool init(const std::string& config_folder, BlockchainDB* db, HardFork*& hf, const network_type nettype = MAINNET, bool offline = false);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note:   candidate expects 5 arguments, 2 provided
make[3]: *** [src/blockchain_utilities/CMakeFiles/blockchain_export.dir/build.make:76: src/blockchain_utilities/CMakeFiles/blockchain_export.dir/blockchain_export.cpp.o] Error 1
make[3]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make[2]: *** [CMakeFiles/Makefile2:3889: src/blockchain_utilities/CMakeFiles/blockchain_export.dir/all] Error 2
In file included from /home/tux/mordinals/src/cryptonote_basic/cryptonote_format_utils.h:33,
                 from /home/tux/mordinals/src/cryptonote_core/cryptonote_tx_utils.h:32,
                 from /home/tux/mordinals/src/cryptonote_core/blockchain.h:59,
                 from /home/tux/mordinals/tests/block_weight/block_weight.cpp:33:
/home/tux/mordinals/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Wdeprecated-declarations]
   43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
      |                             ^~~~~~~~~~~~~~
In file included from /usr/include/c++/12/string:48,
                 from /usr/include/c++/12/stdexcept:39,
                 from /usr/include/boost/asio/io_context.hpp:20,
                 from /usr/include/boost/asio/io_service.hpp:18,
                 from /home/tux/mordinals/src/cryptonote_core/blockchain.h:32:
/usr/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
/home/tux/mordinals/tests/block_weight/block_weight.cpp: In function ‘void test(test_t, uint64_t)’:
/home/tux/mordinals/tests/block_weight/block_weight.cpp:125:28: error: no matching function for call to ‘cryptonote::Blockchain::init({anonymous}::TestDB*, cryptonote::network_type, bool, const cryptonote::test_options*, int, NULL)’
  125 |   bool r = blockchain->init(new TestDB(), cryptonote::FAKECHAIN, true, &opts.test_options, 0, NULL); \
      |            ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tux/mordinals/tests/block_weight/block_weight.cpp:132:28: note: in expansion of macro ‘PREFIX_WINDOW’
  132 | #define PREFIX(hf_version) PREFIX_WINDOW(hf_version, LONG_TERM_BLOCK_WEIGHT_WINDOW)
      |                            ^~~~~~~~~~~~~
/home/tux/mordinals/tests/block_weight/block_weight.cpp:144:3: note: in expansion of macro ‘PREFIX’
  144 |   PREFIX(10);
      |   ^~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::network_type, bool, const cryptonote::test_options*, cryptonote::difficulty_type, const cryptonote::GetCheckpointsCallback&)’
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:34: note:   no known conversion for argument 1 from ‘{anonymous}::TestDB*’ to ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::HardFork*&, cryptonote::network_type, bool)’
  155 |     bool init(const std::string& config_folder, BlockchainDB* db, HardFork*& hf, const network_type nettype = MAINNET, bool offline = false);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note:   candidate expects 5 arguments, 6 provided
make[3]: *** [tests/block_weight/CMakeFiles/block_weight.dir/build.make:76: tests/block_weight/CMakeFiles/block_weight.dir/block_weight.cpp.o] Error 1
make[3]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make[2]: *** [CMakeFiles/Makefile2:5481: tests/block_weight/CMakeFiles/block_weight.dir/all] Error 2
In file included from /home/tux/mordinals/src/cryptonote_core/tx_pool.h:47,
                 from /home/tux/mordinals/src/cryptonote_core/cryptonote_core.h:45,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_prune.cpp:37:
/home/tux/mordinals/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Wdeprecated-declarations]
   43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
      |                             ^~~~~~~~~~~~~~
In file included from /usr/include/c++/12/string:48,
                 from /usr/include/boost/algorithm/string/std/string_traits.hpp:15,
                 from /usr/include/boost/algorithm/string/std_containers_traits.hpp:19,
                 from /usr/include/boost/algorithm/string.hpp:18,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_prune.cpp:32:
/usr/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
/home/tux/mordinals/src/blockchain_utilities/blockchain_prune.cpp: In function ‘int main(int, char**)’:
/home/tux/mordinals/src/blockchain_utilities/blockchain_prune.cpp:625:30: error: no matching function for call to ‘cryptonote::Blockchain::init(cryptonote::BlockchainDB*&, cryptonote::network_type&)’
  625 |     r = core_storage[n]->init(db, net_type);
      |         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /home/tux/mordinals/src/cryptonote_core/cryptonote_core.h:46:
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::network_type, bool, const cryptonote::test_options*, cryptonote::difficulty_type, const cryptonote::GetCheckpointsCallback&)’
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:34: note:   no known conversion for argument 1 from ‘cryptonote::BlockchainDB*’ to ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::HardFork*&, cryptonote::network_type, bool)’
  155 |     bool init(const std::string& config_folder, BlockchainDB* db, HardFork*& hf, const network_type nettype = MAINNET, bool offline = false);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note:   candidate expects 5 arguments, 2 provided
make[3]: *** [src/blockchain_utilities/CMakeFiles/blockchain_prune.dir/build.make:76: src/blockchain_utilities/CMakeFiles/blockchain_prune.dir/blockchain_prune.cpp.o] Error 1
make[3]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make[2]: *** [CMakeFiles/Makefile2:4202: src/blockchain_utilities/CMakeFiles/blockchain_prune.dir/all] Error 2
In file included from /home/tux/mordinals/src/cryptonote_core/tx_pool.h:47,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_prune_known_spent_data.cpp:33:
/home/tux/mordinals/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Wdeprecated-declarations]
   43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
      |                             ^~~~~~~~~~~~~~
In file included from /usr/include/c++/12/string:48,
                 from /usr/include/boost/algorithm/string/std/string_traits.hpp:15,
                 from /usr/include/boost/algorithm/string/std_containers_traits.hpp:19,
                 from /usr/include/boost/algorithm/string.hpp:18,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_prune_known_spent_data.cpp:29:
/usr/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
/home/tux/mordinals/src/blockchain_utilities/blockchain_prune_known_spent_data.cpp: In function ‘int main(int, char**)’:
/home/tux/mordinals/src/blockchain_utilities/blockchain_prune_known_spent_data.cpp:185:25: error: no matching function for call to ‘cryptonote::Blockchain::init(cryptonote::BlockchainDB*&, cryptonote::network_type&)’
  185 |   r = core_storage->init(db, net_type);
      |       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /home/tux/mordinals/src/cryptonote_core/cryptonote_core.h:46,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_prune_known_spent_data.cpp:34:
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::network_type, bool, const cryptonote::test_options*, cryptonote::difficulty_type, const cryptonote::GetCheckpointsCallback&)’
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:34: note:   no known conversion for argument 1 from ‘cryptonote::BlockchainDB*’ to ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::HardFork*&, cryptonote::network_type, bool)’
  155 |     bool init(const std::string& config_folder, BlockchainDB* db, HardFork*& hf, const network_type nettype = MAINNET, bool offline = false);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note:   candidate expects 5 arguments, 2 provided
make[3]: *** [src/blockchain_utilities/CMakeFiles/blockchain_prune_known_spent_data.dir/build.make:76: src/blockchain_utilities/CMakeFiles/blockchain_prune_known_spent_data.dir/blockchain_prune_known_spent_data.cpp.o] Error 1
make[3]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make[2]: *** [CMakeFiles/Makefile2:4156: src/blockchain_utilities/CMakeFiles/blockchain_prune_known_spent_data.dir/all] Error 2
In file included from /home/tux/mordinals/src/cryptonote_core/tx_pool.h:47,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_stats.cpp:34:
/home/tux/mordinals/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Wdeprecated-declarations]
   43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
      |                             ^~~~~~~~~~~~~~
In file included from /usr/include/c++/12/string:48,
                 from /usr/include/boost/algorithm/string/std/string_traits.hpp:15,
                 from /usr/include/boost/algorithm/string/std_containers_traits.hpp:19,
                 from /usr/include/boost/algorithm/string.hpp:18,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_stats.cpp:29:
/usr/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
/home/tux/mordinals/src/blockchain_utilities/blockchain_stats.cpp: In function ‘int main(int, char**)’:
/home/tux/mordinals/src/blockchain_utilities/blockchain_stats.cpp:228:25: error: no matching function for call to ‘cryptonote::Blockchain::init(cryptonote::BlockchainDB*&, cryptonote::network_type&)’
  228 |   r = core_storage->init(db, net_type);
      |       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /home/tux/mordinals/src/cryptonote_core/cryptonote_core.h:46,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_stats.cpp:35:
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::network_type, bool, const cryptonote::test_options*, cryptonote::difficulty_type, const cryptonote::GetCheckpointsCallback&)’
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:34: note:   no known conversion for argument 1 from ‘cryptonote::BlockchainDB*’ to ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::HardFork*&, cryptonote::network_type, bool)’
  155 |     bool init(const std::string& config_folder, BlockchainDB* db, HardFork*& hf, const network_type nettype = MAINNET, bool offline = false);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note:   candidate expects 5 arguments, 2 provided
make[3]: *** [src/blockchain_utilities/CMakeFiles/blockchain_stats.dir/build.make:76: src/blockchain_utilities/CMakeFiles/blockchain_stats.dir/blockchain_stats.cpp.o] Error 1
make[3]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make[2]: *** [CMakeFiles/Makefile2:4110: src/blockchain_utilities/CMakeFiles/blockchain_stats.dir/all] Error 2
In file included from /home/tux/mordinals/src/cryptonote_core/tx_pool.h:47,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_ancestry.cpp:40:
/home/tux/mordinals/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Wdeprecated-declarations]
   43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
      |                             ^~~~~~~~~~~~~~
In file included from /usr/include/c++/12/unordered_map:44,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_ancestry.cpp:29:
/usr/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
/home/tux/mordinals/src/blockchain_utilities/blockchain_ancestry.cpp: In function ‘int main(int, char**)’:
/home/tux/mordinals/src/blockchain_utilities/blockchain_ancestry.cpp:475:25: error: no matching function for call to ‘cryptonote::Blockchain::init(cryptonote::BlockchainDB*&, cryptonote::network_type&)’
  475 |   r = core_storage->init(db, net_type);
      |       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /home/tux/mordinals/src/cryptonote_core/cryptonote_core.h:46,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_ancestry.cpp:41:
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::network_type, bool, const cryptonote::test_options*, cryptonote::difficulty_type, const cryptonote::GetCheckpointsCallback&)’
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:34: note:   no known conversion for argument 1 from ‘cryptonote::BlockchainDB*’ to ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::HardFork*&, cryptonote::network_type, bool)’
  155 |     bool init(const std::string& config_folder, BlockchainDB* db, HardFork*& hf, const network_type nettype = MAINNET, bool offline = false);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note:   candidate expects 5 arguments, 2 provided
make[3]: *** [src/blockchain_utilities/CMakeFiles/blockchain_ancestry.dir/build.make:76: src/blockchain_utilities/CMakeFiles/blockchain_ancestry.dir/blockchain_ancestry.cpp.o] Error 1
make[3]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make[2]: *** [CMakeFiles/Makefile2:4024: src/blockchain_utilities/CMakeFiles/blockchain_ancestry.dir/all] Error 2
In file included from /home/tux/mordinals/src/cryptonote_core/tx_pool.h:47,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_depth.cpp:34:
/home/tux/mordinals/src/cryptonote_basic/cryptonote_basic_impl.h:43:29: warning: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Wdeprecated-declarations]
   43 |   struct array_hasher: std::unary_function<t_array&, std::size_t>
      |                             ^~~~~~~~~~~~~~
In file included from /usr/include/c++/12/string:48,
                 from /usr/include/c++/12/stdexcept:39,
                 from /usr/include/boost/optional/bad_optional_access.hpp:15,
                 from /usr/include/boost/optional/optional.hpp:32,
                 from /usr/include/boost/range/detail/default_constructible_unary_fn.hpp:13,
                 from /usr/include/boost/range/adaptor/transformed.hpp:15,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_depth.cpp:29:
/usr/include/c++/12/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
/home/tux/mordinals/src/blockchain_utilities/blockchain_depth.cpp: In function ‘int main(int, char**)’:
/home/tux/mordinals/src/blockchain_utilities/blockchain_depth.cpp:162:25: error: no matching function for call to ‘cryptonote::Blockchain::init(cryptonote::BlockchainDB*&, cryptonote::network_type&)’
  162 |   r = core_storage->init(db, net_type);
      |       ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
In file included from /home/tux/mordinals/src/cryptonote_core/cryptonote_core.h:46,
                 from /home/tux/mordinals/src/blockchain_utilities/blockchain_depth.cpp:35:
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::network_type, bool, const cryptonote::test_options*, cryptonote::difficulty_type, const cryptonote::GetCheckpointsCallback&)’
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:142:34: note:   no known conversion for argument 1 from ‘cryptonote::BlockchainDB*’ to ‘const std::string&’ {aka ‘const std::__cxx11::basic_string<char>&’}
  142 |     bool init(const std::string& config_folder, BlockchainDB* db, const network_type nettype = MAINNET, bool offline = false, const cryptonote::test_options *test_options = NULL, difficulty_type fixed_difficulty = 0, const GetCheckpointsCallback& get_checkpoints = nullptr);
      |               ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note: candidate: ‘bool cryptonote::Blockchain::init(const std::string&, cryptonote::BlockchainDB*, cryptonote::HardFork*&, cryptonote::network_type, bool)’
  155 |     bool init(const std::string& config_folder, BlockchainDB* db, HardFork*& hf, const network_type nettype = MAINNET, bool offline = false);
      |          ^~~~
/home/tux/mordinals/src/cryptonote_core/blockchain.h:155:10: note:   candidate expects 5 arguments, 2 provided
make[3]: *** [src/blockchain_utilities/CMakeFiles/blockchain_depth.dir/build.make:76: src/blockchain_utilities/CMakeFiles/blockchain_depth.dir/blockchain_depth.cpp.o] Error 1
make[3]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make[2]: *** [CMakeFiles/Makefile2:4067: src/blockchain_utilities/CMakeFiles/blockchain_depth.dir/all] Error 2
make[2]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make[1]: *** [Makefile:146: all] Error 2
make[1]: Leaving directory '/home/tux/mordinals/build/Linux/master/release'
make: *** [Makefile:103: release-all] Error 2`

**Comment by cryptoguard** [comment]
Getting a similar error using Linux. Tried to build normally, and through the Docker method. Both fail with similar errors as OP.

**Comment by Auroleius** [comment]
Yep, same error on macOS after fixing the first two

**Comment by moneroshill** [comment]
I figured out what the problem is, but I won't tell you yet because I want to make ordinals first!

**Comment by moneroshill** [comment]
read the instructions more closely.

**Comment by tuxpizza** [comment]
Since @moneroshill is very unhelpful and I figured it out myself I'll give you guys the fix  (BTW the instructions are not great).
It says to target "simplewallet" with make however simplewallet is not a valid target if you do `make simplewallet` in the root directory (Which is what targeting *actually* means for make) however you have to go into /build/Linux/master/release/src/simplewallet then run `make` there. After that the binary will show up under /build/Linux/master/release/bin

**Comment by keepitcasual** [comment]
hey tuxpizza, when the files are initially downloaded, there is no /build file. Are you saying you run make in root, then after the initial make creates the /build/Linux/master/release/src/simplewallet path, you make there as well? I have tried doing this but get errors when I target make simplewallet in the folder you mentioned. I wonder if it is because the initial root make, which throws up errors and doesn't complete properly... is not making the simplewallet makefile correctly... 

Any insight you can provide would be great. Cheers

**Comment by moneroshill** [comment]
I added more clear instructions in my patch request
