### ISSUE TITLE
Unknown command 'mint_ordinal'

### ISSUE THREAD

**Issue by MaslDi** [mooonero/mordinals#7]
[wallet 46nakZ]: mint_ordinal 0.00001 /home/images/my_inscription.png /home/description.txt  mint_ordinal 0.00001 /home/images/my_inscription.png /home/description.txt

Error: Unknown command 'mint_ordinal', try 'help'

**Comment by bigtimedeveloper** [comment]
that command is only for the mordinals monero-wallet-cli
Build by running make simplewallet in the /mordinals/build/Linux/master/release/src/simplewallet
and
make daemon in the /mordinals/build/Linux/master/release/src/daemon
then run ./monerod and ./monero-wallet-cli
